// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a backfill operation
 */
export type BackfillInfo = { 
/**
 * Unique hash identifying this specific backfill operation
 */
backfill_hash: string, 
/**
 * Transform ID being backfilled
 */
transform_id: string, 
/**
 * Schema name
 */
schema_name: string, 
/**
 * Current status
 */
status: BackfillStatus, 
/**
 * When the backfill started (Unix timestamp in seconds)
 */
start_time: number, 
/**
 * When the backfill completed (if finished)
 */
end_time: number, 
/**
 * Error message if failed
 */
error: string | null, 
/**
 * Records produced by the backfill
 */
records_produced: number, 
/**
 * Expected number of mutations to be created (for completion tracking)
 */
mutations_expected: number, 
/**
 * Number of mutations completed so far
 */
mutations_completed: number, 
/**
 * Number of mutations that failed
 */
mutations_failed: number, };

/**
 * Status of a backfill operation
 */
export type BackfillStatus = "InProgress" | "Completed" | "Failed";

/**
 * Represents the schema-level type information.
 */
export type DeclarativeSchemaType = "Single" | { "Range": { keyconfig: KeyConfig, } } | { "HashRange": { keyconfig: KeyConfig, } };

/**
 * HashRange filter operations for querying hash-range fields
 */
export type HashRangeFilter = { "HashRangeKey": { hash: string, range: string, } } | { "HashKey": string } | { "HashRangePrefix": { hash: string, prefix: string, } } | { "RangePrefix": string } | { "HashRangeRange": { hash: string, start: string, end: string, } } | { "RangeRange": { start: string, end: string, } } | { "SampleN": number } | { "Value": string } | { "HashRangeKeys": Array<[string, string]> } | { "HashRangePattern": { hash: string, pattern: string, } } | { "RangePattern": string } | { "HashPattern": string } | { "HashRange": { start: string, end: string, } };

/**
 * Result of a hash-range filter operation
 */
export type HashRangeFilterResult = { 
/**
 * Matches with composite keys in format "KeyValue" -> atom_uuid
 */
matches: { [key in KeyValue]?: string }, 
/**
 * Total count of matches found
 */
total_count: number, 
/**
 * Number of hash groups that had matches
 */
hash_groups_count: number, };

export type KeyConfig = { hash_field: string | null, range_field: string | null, };

/**
 * Represents resolved key values for hash and range components.
 */
export type KeyValue = { hash: string | null, range: string | null, };
