// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyConfig = { hash_field: string | null, range_field: string | null, };

/**
 * Defines the structure, permissions, and payment requirements for a data collection.
 *
 * A Schema is the fundamental building block for data organization in the database.
 * It defines:
 * - The collection's name and identity
 * - Field definitions with their types and constraints
 * - Field-level permission policies
 * - Payment requirements for data access
 * - Field mappings for schema transformation
 *
 * Schemas provide a contract for data storage and access, ensuring:
 * - Consistent data structure
 * - Proper access control
 * - Payment validation
 * - Data transformation rules
 */
export type Schema = { 
/**
 * Unique name identifying this schema
 */
name: string, 
/**
 * The type of schema. Defaults to a key range schema.
 */
schema_type: SchemaType, 
/**
 * Universal key configuration for all schema types
 */
key: KeyConfig | null, 
/**
 * Collection of fields with their definitions and configurations
 */
fields: Record<string, any>, 
/**
 * SHA256 hash of the schema content for integrity verification
 */
hash: string | null, };

/**
 * Represents the schema-level type information.
 */
export type SchemaType = "Single" | { "Range": { keyconfig: KeyConfig, } } | { "HashRange": { keyconfig: KeyConfig, } };
