// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a backfill operation
 */
export type BackfillInfo = { 
/**
 * Unique hash identifying this specific backfill operation
 */
backfill_hash: string, 
/**
 * Transform ID being backfilled
 */
transform_id: string, 
/**
 * Source schema name
 */
source_schema: string, 
/**
 * Current status
 */
status: BackfillStatus, 
/**
 * When the backfill started (Unix timestamp in seconds)
 */
start_time: number, 
/**
 * When the backfill completed (if finished)
 */
end_time: number, 
/**
 * Error message if failed
 */
error: string | null, 
/**
 * Records produced by the backfill
 */
records_produced: number, 
/**
 * Expected number of mutations to be created (for completion tracking)
 */
mutations_expected: number, 
/**
 * Number of mutations completed so far
 */
mutations_completed: number, 
/**
 * Number of mutations that failed
 */
mutations_failed: number, };

/**
 * Status of a backfill operation
 */
export type BackfillStatus = "InProgress" | "Completed" | "Failed";
