// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Handler-level error types
 */
export type HandlerError = { "BadRequest": string } | { "Unauthorized": string } | { "NotFound": string } | { "Internal": string } | { "ServiceUnavailable": string };
