// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../serde_json/JsonValue";

/**
 * Response for native index search
 */
export type IndexSearchResponse = { 
/**
 * Search results
 */
results: JsonValue, };
