// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for mutation execution
 */
export type MutationResponse = { 
/**
 * The mutation IDs that were executed
 */
mutation_ids: Array<string>, 
/**
 * Number of mutations executed
 */
count: number, };
