// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for node key
 */
export type NodeKeyResponse = { success: boolean, key: string, message: string, };
