// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../serde_json/JsonValue";

/**
 * Response for a single schema
 */
export type SchemaResponse = { 
/**
 * The schema data
 */
schema: JsonValue, };
