// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for schema load operation
 */
export type SchemaLoadResponse = { 
/**
 * Number of available schemas found
 */
available_schemas_loaded: number, 
/**
 * Number successfully loaded to DB
 */
schemas_loaded_to_db: number, 
/**
 * List of failed schema names
 */
failed_schemas: Array<string>, };
