// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../serde_json/JsonValue";

/**
 * Response for listing schemas
 */
export type SchemaListResponse = { 
/**
 * List of schemas with their states
 */
schemas: JsonValue, 
/**
 * Total count
 */
count: number, };
