// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for schema approval
 */
export type SchemaApproveResponse = { 
/**
 * Backfill hash if transform, null otherwise
 */
backfill_hash: string | null, };
