// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single mutation response (for backward compatibility with existing API)
 */
export type SingleMutationResponse = { 
/**
 * The mutation ID
 */
mutation_id: string, 
/**
 * Success flag
 */
success: boolean, };
