// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for system status
 */
export type SystemStatusResponse = { status: string, uptime: bigint, version: string, };
