// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for transform queue
 */
export type TransformQueueResponse = { length: number, queued_transforms: Array<string>, };
