#!/bin/bash
# Sync TypeScript bindings generated by ts-rs from Rust to the frontend

set -e

# Colors for output
GREEN='\033[0.32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Generating TypeScript bindings from Rust types...${NC}"

# Run tests to generate the bindings (ts-rs exports happen during test compilation)
cargo test --lib export_bindings --quiet

echo -e "${BLUE}Copying generated bindings to frontend...${NC}"

# Copy the generated file to the frontend source directory
cp bindings/src/datafold_node/static-react/src/types/generated.ts \
   src/datafold_node/static-react/src/types/generated.ts

echo -e "${GREEN}✓ TypeScript bindings synced successfully${NC}"
echo ""
echo "Generated types:"
grep "^export type" src/datafold_node/static-react/src/types/generated.ts | sed 's/export type \([^ =]*\).*/  - \1/'

