// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TopologyNode } from "./TopologyNode";

/**
 * Represents the topology (structure) of a JSON field
 */
export type JsonTopology = { 
/**
 * Root structure definition
 */
root: TopologyNode, };
