// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Primitive JSON value types
 */
export type PrimitiveValueType = "String" | "Number" | "Boolean" | "Null";
