// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimitiveValueType } from "./PrimitiveValueType";

/**
 * Represents a node in the JSON topology tree
 */
export type TopologyNode = { "type": "Primitive", value: PrimitiveValueType, classifications: Array<string> | null, } | { "type": "Object", value: { [key in string]?: TopologyNode }, } | { "type": "Array", value: TopologyNode, } | { "type": "Any" };
