// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimitiveType } from "./PrimitiveType";

/**
 * Represents a node in the JSON topology tree
 */
export type TopologyNode = { "type": "Primitive", "value": PrimitiveType } | { "type": "Object", "value": { [key in string]?: TopologyNode } } | { "type": "Array", "value": TopologyNode } | { "type": "Any" };
