// AUTO-GENERATED by scripts/generate-endpoints.js from file:///Users/tomtang/Projects/folddb/fold_db/src/datafold_node/static-react/../../../target/openapi.json
// Do not edit manually. Run: npm run generate:endpoints

import type { paths } from '../types/openapi'

type PathParams<P extends keyof paths, M extends keyof paths[P]> =
  paths[P][M] extends { parameters: { path: infer T } } ? T : Record<string, string>

export const API_ENDPOINTS_DERIVED = {
  GET_INGESTION_CONFIG: '/ingestion/config',
  HEALTH_CHECK: '/ingestion/health',
  PROCESS_JSON: '/ingestion/process',
  GET_STATUS: '/ingestion/status',
  VALIDATE_JSON: '/ingestion/validate',
  LIST_LOGS: '/logs',
  GET_CONFIG: '/logs/config',
  RELOAD_CONFIG: '/logs/config/reload',
  GET_FEATURES: '/logs/features',
  UPDATE_FEATURE_LEVEL: '/logs/level',
  STREAM_LOGS: '/logs/stream',
  EXECUTE_MUTATION: '/mutation',
  EXECUTE_QUERY: '/query',
  GET_SCHEMA: (name: PathParams<'/api/schema/{name}', 'get'>['name']) => `/schema/${name}`,
  APPROVE_SCHEMA: (name: PathParams<'/api/schema/{name}/approve', 'post'>['name']) => `/schema/${name}/approve`,
  BLOCK_SCHEMA: (name: PathParams<'/api/schema/{name}/block', 'post'>['name']) => `/schema/${name}/block`,
  LIST_SCHEMAS: '/schemas',
  LOAD_SCHEMAS: '/schemas/load',
  GET_SYSTEM_PUBLIC_KEY: '/security/system-key',
  GET_NODE_PRIVATE_KEY: '/system/private-key',
  GET_NODE_PUBLIC_KEY: '/system/public-key',
  RESET_DATABASE: '/system/reset-database',
  GET_SYSTEM_STATUS: '/system/status',
  LIST_TRANSFORMS: '/transforms',
  GET_TRANSFORM_QUEUE: '/transforms/queue',
  ADD_TO_TRANSFORM_QUEUE: (id: PathParams<'/api/transforms/queue/{id}', 'post'>['id']) => `/transforms/queue/${id}`,
} as const;

// Base URL prefixes derived from OpenAPI paths
export const API_BASE_URLS = {
  ROOT: '/api',
  INGESTION: '/api/ingestion',
  LOGS: '/api/logs',
  MUTATION: '/api/mutation',
  QUERY: '/api/query',
  SCHEMA: '/api/schema',
  SCHEMAS: '/api/schemas',
  SECURITY: '/api/security',
  SYSTEM: '/api/system',
  TRANSFORMS: '/api/transforms',
} as const;

export const API_ENDPOINTS_ALIASES = {
  MUTATION: '/mutation',
  QUERY: '/query',
  SCHEMAS_BASE: '/schemas',
  SCHEMA_BY_NAME: (name: PathParams<'/api/schema/{name}', 'get'>['name']) => `/schema/${name}`,
  SCHEMA_APPROVE: (name: PathParams<'/api/schema/{name}/approve', 'post'>['name']) => `/schema/${name}/approve`,
  SCHEMA_BLOCK: (name: PathParams<'/api/schema/{name}/block', 'post'>['name']) => `/schema/${name}/block`,
  SYSTEM_STATUS: '/system/status',
  SYSTEM_LOGS: '/logs',
  SYSTEM_LOGS_STREAM: '/logs/stream',
  SYSTEM_RESET_DATABASE: '/system/reset-database',
  SYSTEM_PRIVATE_KEY: '/system/private-key',
  SYSTEM_PUBLIC_KEY: '/system/public-key',
  TRANSFORMS: '/transforms',
  TRANSFORMS_QUEUE: '/transforms/queue',
  TRANSFORMS_QUEUE_ADD: (id: PathParams<'/api/transforms/queue/{id}', 'post'>['id']) => `/transforms/queue/${id}`,
  INGESTION_STATUS: '/ingestion/status',
  INGESTION_CONFIG: '/ingestion/config',
  INGESTION_VALIDATE: '/ingestion/validate',
  INGESTION_PROCESS: '/ingestion/process',
  INGESTION_HEALTH: '/ingestion/health',
} as const;

export const API_ENDPOINTS = { ...API_ENDPOINTS_DERIVED, ...API_ENDPOINTS_ALIASES } as const;
export type ApiEndpoint = typeof API_ENDPOINTS[keyof typeof API_ENDPOINTS];
