// AUTO-GENERATED by scripts/generate-endpoints.js from file:///tmp/openapi.json
// Do not edit manually. Run: npm run generate:endpoints

export const API_ENDPOINTS_DERIVED = {
  GET_INGESTION_CONFIG: '/ingestion/config',
  HEALTH_CHECK: '/ingestion/health',
  PROCESS_JSON: '/ingestion/process',
  GET_STATUS: '/ingestion/status',
  VALIDATE_JSON: '/ingestion/validate',
  LIST_LOGS: '/logs',
  GET_CONFIG: '/logs/config',
  RELOAD_CONFIG: '/logs/config/reload',
  GET_FEATURES: '/logs/features',
  UPDATE_FEATURE_LEVEL: '/logs/level',
  STREAM_LOGS: '/logs/stream',
  EXECUTE_MUTATION: '/mutation',
  EXECUTE_QUERY: '/query',
  GET_SCHEMA: (name) => `/schema/${name}`,
  APPROVE_SCHEMA: (name) => `/schema/${name}/approve`,
  BLOCK_SCHEMA: (name) => `/schema/${name}/block`,
  LIST_SCHEMAS: '/schemas',
  GET_SYSTEM_PUBLIC_KEY: '/security/system-key',
  GET_NODE_PRIVATE_KEY: '/system/private-key',
  GET_NODE_PUBLIC_KEY: '/system/public-key',
  RESET_DATABASE: '/system/reset-database',
  GET_SYSTEM_STATUS: '/system/status',
  LIST_TRANSFORMS: '/transforms',
  GET_TRANSFORM_QUEUE: '/transforms/queue',
  ADD_TO_TRANSFORM_QUEUE: (id) => `/transforms/queue/${id}`,
} as const;

export const API_ENDPOINTS = API_ENDPOINTS_DERIVED;
export type ApiEndpoint = typeof API_ENDPOINTS[keyof typeof API_ENDPOINTS];
